image:
  file: .gitpod/Dockerfile

tasks:
  - name: Flutter env prep
    before: |
      flutter pub get

ports:
  - port: 5900
    onOpen: ignore
    name: VNC Server
  - port: 6080
    onOpen: ignore
    name: VNC Client
    description: noVNC web client
  - port: 8080
    onOpen: ignore
    name: Flutter Web
    visibility: public
  - port: 9100-9199
    name: Flutter DevTools
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore
    name: Flutter Internals
  - port: 5037
    onOpen: ignore
    name: ADB
  - port: 6000
    onOpen: ignore
    name: Appetize SSH Tunnel

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - editorconfig.editorconfig
    - ms-azuretools.vscode-docker
